services:
  - type: web
    name: college-notes-rag
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.0-flash
      - key: GEMINI_EMBEDDING_MODEL
        value: gemini-embedding-001
